### ISSUE TITLE
Install iotdb-homestar in Ubuntu 15.04

### ISSUE THREAD

**Issue by lboue** [dpjanes/iotdb-homestar#2]
Hello,

I am tring to install iotdb-homestar in Ubuntu 15.04 but it fails. Could you help me to fix that?

<pre>
sudo apt-get install npm node
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Les NOUVEAUX paquets suivants seront installés :
  node npm
0 mis à jour, 2 nouvellement installés, 0 à enlever et 22 non mis à jour.
Il est nécessaire de prendre 354 ko dans les archives.
Après cette opération, 1 955 ko d'espace disque supplémentaires seront utilisés.
Réception de : 1 http://fr.archive.ubuntu.com/ubuntu/ vivid/universe node all 0.3.2-7.4 [1 284 B]
Réception de : 2 http://fr.archive.ubuntu.com/ubuntu/ vivid/universe npm all 1.4.21+ds-2 [353 kB]
354 ko réceptionnés en 0s (378 ko/s)
Sélection du paquet node précédemment désélectionné.
(Lecture de la base de données... 176316 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../node_0.3.2-7.4_all.deb ...
Dépaquetage de node (0.3.2-7.4) ...
Sélection du paquet npm précédemment désélectionné.
Préparation du dépaquetage de .../npm_1.4.21+ds-2_all.deb ...
Dépaquetage de npm (1.4.21+ds-2) ...
Traitement des actions différées (« triggers ») pour man-db (2.7.0.2-5) ...
Traitement des actions différées (« triggers ») pour doc-base (0.10.6) ...
Traitement de 4 fichiers de documentation ajoutés…
Paramétrage de node (0.3.2-7.4) ...
Paramétrage de npm (1.4.21+ds-2) ...

sudo npm install -g homestar
 
> dtrace-provider@0.4.0 install /usr/local/lib/node_modules/homestar/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm WARN optional dep failed, continuing dtrace-provider@0.4.0
 
> ws@0.4.32 install /usr/local/lib/node_modules/homestar/node_modules/mows/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

 
> utf-8-validate@1.0.1 install /usr/local/lib/node_modules/homestar/node_modules/mqtt/node_modules/websocket-stream/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.19.0-15-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homestar/node_modules/mqtt/node_modules/websocket-stream/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 

> bufferutil@1.0.1 install /usr/local/lib/node_modules/homestar/node_modules/mqtt/node_modules/websocket-stream/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.19.0-15-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homestar/node_modules/mqtt/node_modules/websocket-stream/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing utf-8-validate@1.0.1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm WARN optional dep failed, continuing bufferutil@1.0.1
/usr/local/bin/homestar -> /usr/local/lib/node_modules/homestar/bin/homestar
homestar@0.1.1 /usr/local/lib/node_modules/homestar
├── connect-fs@0.1.1
├── open@0.0.5
├── minimist@1.1.1
├── uuid@2.0.1
├── cookie-parser@1.3.4 (cookie-signature@1.0.6, cookie@0.1.2)
├── passport@0.2.1 (pause@0.0.1, passport-strategy@1.0.0)
├── express-session@1.11.1 (utils-merge@1.0.0, cookie-signature@1.0.6, cookie@0.1.2, parseurl@1.3.0, on-headers@1.0.0, depd@1.0.1, crc@3.2.1, uid-safe@1.1.0, debug@2.1.3)
├── iotdb-transport-iotdb@0.0.2 (validate@2.1.6)
├── iotdb@0.6.7 (canonical-json@0.0.4, node-uuid@1.4.3, underscore@1.8.3)
├── passport-twitter@1.0.3 (xtraverse@0.1.0, passport-oauth1@1.0.1)
├── body-parser@1.12.3 (content-type@1.0.1, bytes@1.0.0, raw-body@1.3.4, depd@1.0.1, on-finished@2.2.1, qs@2.4.1, debug@2.1.3, type-is@1.6.1, iconv-lite@0.4.8)
├── iotdb-transport-express@0.0.3 (validate@2.1.6)
├── iotdb-transport-fs@0.0.6 (mkdirp@0.5.0, watch@0.16.0, validate@2.1.6)
├── express@4.12.3 (merge-descriptors@1.0.0, utils-merge@1.0.0, cookie-signature@1.0.6, methods@1.1.1, cookie@0.1.2, fresh@0.2.4, range-parser@1.0.2, escape-html@1.0.1, content-type@1.0.1, finalhandler@0.3.4, vary@1.0.0, parseurl@1.3.0, serve-static@1.9.2, content-disposition@0.5.0, path-to-regexp@0.1.3, on-finished@2.2.1, depd@1.0.1, etag@1.5.1, qs@2.4.1, send@0.12.2, debug@2.1.3, proxy-addr@1.0.7, accepts@1.2.6, type-is@1.6.1)
├── session-file-store@0.0.8 (retry@0.6.1, fs-extra@0.18.3)
├── unirest@0.4.0 (mime@1.2.11, form-data@0.2.0, request@2.51.0)
├── bunyan@1.3.5 (safe-json-stringify@1.0.3, mv@2.0.3)
├── prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.3.0, read@1.0.5, winston@0.8.3, utile@0.2.1)
├── iotdb-transport-mqtt@0.0.3 (validate@2.1.6)
├── iotdb-transport-firebase@0.0.8 (validate@2.1.6, firebase@2.2.4)
├── mows@0.0.6 (websocket-stream@0.5.1, mqtt@0.3.13, ws@0.4.32)
├── iotdb-timers@0.0.10 (suncalc@1.6.0, moment@2.9.0)
├── swig@1.4.2 (optimist@0.6.1, uglify-js@2.4.21)
└── mqtt@1.1.4 (inherits@2.0.1, xtend@4.0.0, commist@1.0.0, end-of-stream@1.1.0, mqtt-packet@3.2.0, readable-stream@1.0.33, help-me@0.1.0, concat-stream@1.4.8, mqtt-connection@2.1.1, websocket-stream@1.5.0)
</pre>

Regards

**Comment by dpjanes** [comment]
I think you have an old version of node installed (0.10.25) 
You should be seeing node -v giving "0.12.2".

Here's the error messages from above:

gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2

**Comment by lboue** [comment]
OK. Thanks
