### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by joedix** [dpjanes/iotdb-homestar#3]
homestar install homestar-smart-things is listed at https://github.com/dpjanes/iotdb-homestar/blob/master/docs/modules.md, the npm is homestar-smartthings.
This generated a not found error.

**Comment by dpjanes** [comment]
Fixed, thanks

**Comment by nzhome** [comment]
hi joedix, did that fix it? if so, you can close the issue. thanks.

**Comment by dpjanes** [comment]
Note also we've up-versioned IOTDB. If things aren't working, try "homestar update"
